// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'my_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD849zwkcS-XlIXpgvAILlLiOhbbO3YgU',
    appId: '1:172695366844:web:1e8d2b0c4689b6c76cb4b9',
    messagingSenderId: '172695366844',
    projectId: 'flutterfeed-5cd86',
    authDomain: 'flutterfeed-5cd86.firebaseapp.com',
    storageBucket: 'flutterfeed-5cd86.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFMvkxlAwHI1VUaaof30NWZKrQDGQ-anA',
    appId: '1:172695366844:android:b956197757a950c16cb4b9',
    messagingSenderId: '172695366844',
    projectId: 'flutterfeed-5cd86',
    storageBucket: 'flutterfeed-5cd86.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQafig0xCPR8g2P901sjVbMpJcjPqLZmU',
    appId: '1:172695366844:ios:c622613e521d58e06cb4b9',
    messagingSenderId: '172695366844',
    projectId: 'flutterfeed-5cd86',
    storageBucket: 'flutterfeed-5cd86.appspot.com',
    iosBundleId: 'com.example.flutterfeed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQafig0xCPR8g2P901sjVbMpJcjPqLZmU',
    appId: '1:172695366844:ios:fecaf9b1b503c60e6cb4b9',
    messagingSenderId: '172695366844',
    projectId: 'flutterfeed-5cd86',
    storageBucket: 'flutterfeed-5cd86.appspot.com',
    iosBundleId: 'com.example.flutterfeed.RunnerTests',
  );
}
